name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Snake GIF
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: MansiRK
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.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}}
