 name: gitartwork
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: MansiRK/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: MansiRK
            # Text on contribution graph 
            text: MANSI
       - uses: jasineri/simple-push-action@v1
